# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='identifation',
        ),
        migrations.AddField(
            model_name='user',
            name='identification',
            field=models.CharField(default=None, max_length=30, unique=True, verbose_name='identification'),
            preserve_default=False,
        ),
    ]
