# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20171020_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='address',
            field=models.CharField(default=None, max_length=50, verbose_name='address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='egresado',
            name='career',
            field=models.CharField(max_length=30, verbose_name='career'),
        ),
        migrations.AlterField(
            model_name='egresado',
            name='country',
            field=models.CharField(max_length=30, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=30, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='is_active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='is_staff'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='first last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='second_last_name',
            field=models.CharField(max_length=30, verbose_name='second last name'),
        ),
    ]
