# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20171022_1320'),
    ]

    operations = [
    ]
